# Generated by Django 3.0.8 on 2020-07-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomba',
            name='cod_bomba',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curva',
            name='cod_curva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motor',
            name='cod_motor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
